version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.10.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
